import type { AvatarModelV1, Part, Pseudo3DHeadData } from "@a2d/avatar-schema";
import { createTypedView, type LoadedA2DPackage } from "./packageLoader.js";
import { ParameterCore } from "./parameterCore.js";
import type { GpuTimingInfo } from "./gpuTiming.js";
import { compileVisualRenderPlan, type VisualDrawItem, type VisualRenderPlan } from "./visualPlan.js";
import { decodeVisualTextures, type DecodedVisualTextures } from "./visualTextures.js";
import type { DecodedTexture } from "./textureResources.js";

type DisjointTimerQueryExt={TIME_ELAPSED_EXT:number;GPU_DISJOINT_EXT:number};
type PartGpu={modelIndex:number;part:Part;vao:WebGLVertexArrayObject;buffers:WebGLBuffer[];indexCount:number;indexType:number};
type GlVisualTexture={texture:WebGLTexture;filter:"linear"|"nearest"};
type MaskTarget={texture:WebGLTexture;framebuffer:WebGLFramebuffer;width:number;height:number};
const MAX_VERTEX_INFLUENCES=8;

const VERT=`#version 300 es
precision highp float; precision highp int;
layout(location=0) in vec2 a_position; layout(location=1) in vec2 a_uv; layout(location=2) in float a_proxyZ; layout(location=3) in uvec2 a_influenceRange;
uniform sampler2D u_parameters; uniform sampler2D u_parameterDefs; uniform sampler2D u_morphInfluences; uniform ivec2 u_parameterTexSize; uniform ivec2 u_influenceTexSize;
uniform int u_paramAngleX; uniform int u_paramAngleY; uniform int u_paramAngleZ; uniform vec2 u_headPivot; uniform float u_headDepthScale; uniform float u_headPerspective; uniform float u_headYawGain; uniform float u_headPitchGain;
out vec2 v_uv;
float fetchScalar(sampler2D tex,ivec2 size,int index){return texelFetch(tex,ivec2(index%size.x,index/size.x),0).r;}
vec4 fetchRecord(sampler2D tex,ivec2 size,int index){return texelFetch(tex,ivec2(index%size.x,index/size.x),0);}
float normalizedParameter(int index){if(index<0)return 0.0;float value=fetchScalar(u_parameters,u_parameterTexSize,index);vec4 def=fetchRecord(u_parameterDefs,u_parameterTexSize,index);if(value>=def.b){float d=def.g-def.b;return d==0.0?0.0:clamp((value-def.b)/d,0.0,1.0);}float d=def.b-def.r;return d==0.0?0.0:clamp((value-def.b)/d,-1.0,0.0);}
void main(){vec2 p=a_position;uint n=min(a_influenceRange.y,uint(${MAX_VERTEX_INFLUENCES}));for(uint i=0u;i<uint(${MAX_VERTEX_INFLUENCES});++i){if(i>=n)break;vec4 rec=fetchRecord(u_morphInfluences,u_influenceTexSize,int(a_influenceRange.x+i));p+=normalizedParameter(int(rec.r+0.5))*rec.a*rec.gb;}float ax=u_paramAngleX>=0?fetchScalar(u_parameters,u_parameterTexSize,u_paramAngleX):0.0;float ay=u_paramAngleY>=0?fetchScalar(u_parameters,u_parameterTexSize,u_paramAngleY):0.0;float az=u_paramAngleZ>=0?fetchScalar(u_parameters,u_parameterTexSize,u_paramAngleZ):0.0;vec2 local=p-u_headPivot;float z0=a_proxyZ*u_headDepthScale;float yaw=radians(ax*u_headYawGain),pitch=radians(ay*u_headPitchGain);float cy=cos(yaw),sy=sin(yaw),cp=cos(pitch),sp=sin(pitch);float x1=cy*local.x+sy*z0;float z1=-sy*local.x+cy*z0;float y1=cp*local.y-sp*z1;float z2=sp*local.y+cp*z1;float scale=1.0/max(0.25,1.0+u_headPerspective*(z2-z0));p=vec2(x1,y1)*scale+u_headPivot;float r=radians(az),cr=cos(r),sr=sin(r);local=p-u_headPivot;p=vec2(cr*local.x-sr*local.y,sr*local.x+cr*local.y)+u_headPivot;gl_Position=vec4(p.x*2.0-1.0,1.0-p.y*2.0,0.0,1.0);v_uv=a_uv;}`;
const MAIN_FRAG=`#version 300 es
precision highp float;in vec2 v_uv;out vec4 outColor;uniform sampler2D u_albedo;uniform sampler2D u_mask;uniform float u_opacity;uniform int u_clipMode;uniform vec2 u_viewport;
void main(){vec4 c=texture(u_albedo,v_uv)*u_opacity;if(u_clipMode!=0){vec2 uv=gl_FragCoord.xy/max(u_viewport,vec2(1.0));float coverage=texture(u_mask,uv).a;c*=u_clipMode==1?coverage:(1.0-coverage);}outColor=c;}`;
const MASK_FRAG=`#version 300 es
precision highp float;in vec2 v_uv;out vec4 outColor;uniform sampler2D u_albedo;uniform float u_opacity;void main(){float a=texture(u_albedo,v_uv).a*u_opacity;outColor=vec4(a,a,a,a);}`;

function compile(gl:WebGL2RenderingContext,type:number,source:string):WebGLShader{const s=gl.createShader(type);if(!s)throw new Error("createShader failed");gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS)){const log=gl.getShaderInfoLog(s);gl.deleteShader(s);throw new Error(`shader compile failed: ${log}`);}return s;}
function makeProgram(gl:WebGL2RenderingContext,frag:string):WebGLProgram{const vs=compile(gl,gl.VERTEX_SHADER,VERT),fs=compile(gl,gl.FRAGMENT_SHADER,frag),p=gl.createProgram();if(!p)throw new Error("createProgram failed");gl.attachShader(p,vs);gl.attachShader(p,fs);gl.linkProgram(p);gl.deleteShader(vs);gl.deleteShader(fs);if(!gl.getProgramParameter(p,gl.LINK_STATUS)){const log=gl.getProgramInfoLog(p);gl.deleteProgram(p);throw new Error(`program link failed: ${log}`);}return p;}
function textureSize(count:number):[number,number]{const w=Math.max(1,Math.min(1024,count));return[w,Math.max(1,Math.ceil(count/w))];}
function setTextureParams(gl:WebGL2RenderingContext,filter:"linear"|"nearest"):void{const f=filter==="nearest"?gl.NEAREST:gl.LINEAR;gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,f);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,f);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);}
function uploadR32F(gl:WebGL2RenderingContext,data:Float32Array,size:[number,number]):WebGLTexture{const t=gl.createTexture();if(!t)throw new Error("texture allocation failed");gl.bindTexture(gl.TEXTURE_2D,t);setTextureParams(gl,"nearest");const padded=new Float32Array(size[0]*size[1]);padded.set(data);gl.texImage2D(gl.TEXTURE_2D,0,gl.R32F,size[0],size[1],0,gl.RED,gl.FLOAT,padded);return t;}
function uploadRGBA32F(gl:WebGL2RenderingContext,data:Float32Array,count:number):{texture:WebGLTexture;size:[number,number]}{const size=textureSize(count),t=gl.createTexture();if(!t)throw new Error("texture allocation failed");gl.bindTexture(gl.TEXTURE_2D,t);setTextureParams(gl,"nearest");const padded=new Float32Array(size[0]*size[1]*4);padded.set(data);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA32F,size[0],size[1],0,gl.RGBA,gl.FLOAT,padded);return{texture:t,size};}
function uploadDecoded(gl:WebGL2RenderingContext,d:DecodedTexture):GlVisualTexture{const t=gl.createTexture();if(!t)throw new Error("visual texture allocation failed");gl.bindTexture(gl.TEXTURE_2D,t);setTextureParams(gl,d.filter);if(d.kind==="rgba8")gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA8,d.width,d.height,0,gl.RGBA,gl.UNSIGNED_BYTE,d.pixels);else gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,d.bitmap);return{texture:t,filter:d.filter};}
function createWhite(gl:WebGL2RenderingContext):GlVisualTexture{const t=gl.createTexture();if(!t)throw new Error("white texture allocation failed");gl.bindTexture(gl.TEXTURE_2D,t);setTextureParams(gl,"nearest");gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA8,1,1,0,gl.RGBA,gl.UNSIGNED_BYTE,new Uint8Array([255,255,255,255]));return{texture:t,filter:"nearest"};}
function sleep(ms:number):Promise<void>{return new Promise(resolve=>setTimeout(resolve,ms));}

export class WebGL2VisualRenderer{
 readonly backend="webgl2" as const;readonly gl:WebGL2RenderingContext;readonly model:AvatarModelV1;readonly parameters:ParameterCore;readonly gpuTiming:GpuTimingInfo;
 private readonly mainProgram:WebGLProgram;private readonly maskProgram:WebGLProgram;private readonly parts:PartGpu[]=[];private readonly partByModelIndex=new Map<number,PartGpu>();private readonly parameterTexture:WebGLTexture;private readonly parameterDefTexture:WebGLTexture;private readonly influenceTexture:WebGLTexture;private readonly parameterTexSize:[number,number];private readonly influenceTexSize:[number,number];private readonly head:Pseudo3DHeadData;private readonly parameterIndices:{x:number;y:number;z:number};private readonly timerExt:DisjointTimerQueryExt|null;private readonly pendingQueries:WebGLQuery[]=[];private readonly gpuTimingSamples:number[]=[];private readonly visualTextures=new Map<string,GlVisualTexture>();private readonly whiteTexture:GlVisualTexture;private readonly plan:VisualRenderPlan;private readonly maskTargets=new Map<string,MaskTarget>();private gpuTimingEnabled=false;
 static async create(canvas:HTMLCanvasElement,pkg:LoadedA2DPackage):Promise<WebGL2VisualRenderer>{const decoded=await decodeVisualTextures(pkg);try{return new WebGL2VisualRenderer(canvas,pkg,decoded);}finally{decoded.dispose();}}
 private constructor(canvas:HTMLCanvasElement,pkg:LoadedA2DPackage,decoded:DecodedVisualTextures){const gl=canvas.getContext("webgl2",{alpha:true,antialias:true,premultipliedAlpha:true});if(!gl)throw new Error("WebGL2 is unavailable");this.gl=gl;this.model=pkg.model;this.parameters=new ParameterCore(pkg.model.parameters);this.plan=compileVisualRenderPlan(pkg.model);this.mainProgram=makeProgram(gl,MAIN_FRAG);this.maskProgram=makeProgram(gl,MASK_FRAG);this.timerExt=gl.getExtension("EXT_disjoint_timer_query_webgl2") as DisjointTimerQueryExt|null;this.gpuTiming=this.timerExt?{supported:true,source:"webgl2-disjoint-timer-query"}:{supported:false,reason:"EXT_disjoint_timer_query_webgl2 is unavailable"};this.parameterTexSize=textureSize(Math.max(1,this.parameters.length));this.parameterTexture=uploadR32F(gl,this.parameters.values,this.parameterTexSize);const defs=new Float32Array(this.parameterTexSize[0]*this.parameterTexSize[1]*4);pkg.model.parameters.forEach((p,i)=>{defs[i*4]=p.min;defs[i*4+1]=p.max;defs[i*4+2]=p.default;});this.parameterDefTexture=uploadRGBA32F(gl,defs,this.parameterTexSize[0]*this.parameterTexSize[1]).texture;const ref=pkg.model.deformationBuffers?.morphInfluences?.view;let infData=new Float32Array(4),infCount=1;if(ref){const source=pkg.buffers.get(ref.buffer);if(!source)throw new Error(`missing influence buffer ${ref.buffer}`);infCount=ref.byteLength/16;infData=new Float32Array(infCount*4);const view=new DataView(source,ref.byteOffset,ref.byteLength);for(let i=0;i<infCount;i++){const b=i*16;infData[i*4]=view.getUint32(b,true);infData[i*4+1]=view.getFloat32(b+4,true);infData[i*4+2]=view.getFloat32(b+8,true);infData[i*4+3]=view.getFloat32(b+12,true);}}const inf=uploadRGBA32F(gl,infData,infCount);this.influenceTexture=inf.texture;this.influenceTexSize=inf.size;const hd=pkg.model.deformers.find(d=>d.type==="pseudo3d_head")?.data as Partial<Pseudo3DHeadData>|undefined;this.head={pivot:hd?.pivot??[0.5,0.5],radius:hd?.radius??[0.5,0.6],depthScale:hd?.depthScale??0,perspective:hd?.perspective??0,yawGain:hd?.yawGain??1,pitchGain:hd?.pitchGain??1};const gi=(id:string)=>this.parameters.indexById.get(id)??-1;this.parameterIndices={x:gi("ParamAngleX"),y:gi("ParamAngleY"),z:gi("ParamAngleZ")};this.whiteTexture=createWhite(gl);for(const[id,t]of decoded.byId)this.visualTextures.set(id,uploadDecoded(gl,t));pkg.model.parts.forEach((part,index)=>{const gpu=this.createPart(pkg,part,index);this.parts.push(gpu);this.partByModelIndex.set(index,gpu);});}
 private createPart(pkg:LoadedA2DPackage,part:Part,modelIndex:number):PartGpu{const{gl}=this,positions=createTypedView(pkg.buffers,part.mesh.positions),uvs=createTypedView(pkg.buffers,part.mesh.uvs),indices=createTypedView(pkg.buffers,part.mesh.indices);if(!(positions instanceof Float32Array)||!(uvs instanceof Float32Array))throw new Error(`${part.id}: positions/uvs must be f32`);if(!(indices instanceof Uint16Array||indices instanceof Uint32Array))throw new Error(`${part.id}: indices must be u16/u32`);const n=positions.length/2;let z=new Float32Array(n),ranges=new Uint32Array(n*2);if(part.mesh.proxyZ){const v=createTypedView(pkg.buffers,part.mesh.proxyZ);if(!(v instanceof Float32Array)||v.length!==n)throw new Error(`${part.id}: invalid proxyZ`);z=v;}if(part.mesh.influenceRanges){const v=createTypedView(pkg.buffers,part.mesh.influenceRanges);if(!(v instanceof Uint32Array)||v.length!==n*2)throw new Error(`${part.id}: invalid influenceRanges`);ranges=v;}const vao=gl.createVertexArray();if(!vao)throw new Error("createVertexArray failed");gl.bindVertexArray(vao);const buffers:WebGLBuffer[]=[];const add=(loc:number,data:Float32Array,size:number)=>{const b=gl.createBuffer();if(!b)throw new Error("buffer allocation failed");buffers.push(b);gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,data,gl.STATIC_DRAW);gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,size,gl.FLOAT,false,0,0);};add(0,positions,2);add(1,uvs,2);add(2,z,1);const rb=gl.createBuffer();if(!rb)throw new Error("buffer allocation failed");buffers.push(rb);gl.bindBuffer(gl.ARRAY_BUFFER,rb);gl.bufferData(gl.ARRAY_BUFFER,ranges,gl.STATIC_DRAW);gl.enableVertexAttribArray(3);gl.vertexAttribIPointer(3,2,gl.UNSIGNED_INT,0,0);const ib=gl.createBuffer();if(!ib)throw new Error("buffer allocation failed");buffers.push(ib);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,ib);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,indices,gl.STATIC_DRAW);gl.bindVertexArray(null);return{modelIndex,part,vao,buffers,indexCount:indices.length,indexType:indices instanceof Uint32Array?gl.UNSIGNED_INT:gl.UNSIGNED_SHORT};}
 setParameter(id:string,value:number):void{this.parameters.set(id,value);}setGpuTimingEnabled(enabled:boolean):void{this.gpuTimingEnabled=enabled&&this.gpuTiming.supported;}
 async collectGpuTimings():Promise<number[]>{if(this.timerExt){const deadline=performance.now()+5000;while(this.pendingQueries.length&&performance.now()<deadline){this.pollGpuQueries();if(this.pendingQueries.length)await sleep(0);}for(const q of this.pendingQueries.splice(0))this.gl.deleteQuery(q);}return this.gpuTimingSamples.splice(0);}
 private pollGpuQueries():void{const ext=this.timerExt;if(!ext||!this.pendingQueries.length)return;const{gl}=this;if(Boolean(gl.getParameter(ext.GPU_DISJOINT_EXT))){for(const q of this.pendingQueries.splice(0))gl.deleteQuery(q);return;}while(this.pendingQueries.length){const q=this.pendingQueries[0];if(!Boolean(gl.getQueryParameter(q,gl.QUERY_RESULT_AVAILABLE)))break;const ms=Number(gl.getQueryParameter(q,gl.QUERY_RESULT))/1_000_000;this.pendingQueries.shift();gl.deleteQuery(q);if(Number.isFinite(ms)&&ms>=0)this.gpuTimingSamples.push(ms);}}
 private flush():void{const r=this.parameters.consumeDirtyRange();if(!r)return;const{gl}=this;gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,this.parameterTexture);let i=r.start;while(i<r.endExclusive){const x=i%this.parameterTexSize[0],y=Math.floor(i/this.parameterTexSize[0]),count=Math.min(this.parameterTexSize[0]-x,r.endExclusive-i);gl.texSubImage2D(gl.TEXTURE_2D,0,x,y,count,1,gl.RED,gl.FLOAT,this.parameters.values.subarray(i,i+count));i+=count;}}
 private common(program:WebGLProgram):void{const{gl}=this,loc=(n:string)=>gl.getUniformLocation(program,n);gl.useProgram(program);gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,this.parameterTexture);gl.uniform1i(loc("u_parameters"),0);gl.activeTexture(gl.TEXTURE1);gl.bindTexture(gl.TEXTURE_2D,this.parameterDefTexture);gl.uniform1i(loc("u_parameterDefs"),1);gl.activeTexture(gl.TEXTURE2);gl.bindTexture(gl.TEXTURE_2D,this.influenceTexture);gl.uniform1i(loc("u_morphInfluences"),2);gl.uniform2i(loc("u_parameterTexSize"),this.parameterTexSize[0],this.parameterTexSize[1]);gl.uniform2i(loc("u_influenceTexSize"),this.influenceTexSize[0],this.influenceTexSize[1]);gl.uniform1i(loc("u_paramAngleX"),this.parameterIndices.x);gl.uniform1i(loc("u_paramAngleY"),this.parameterIndices.y);gl.uniform1i(loc("u_paramAngleZ"),this.parameterIndices.z);gl.uniform2f(loc("u_headPivot"),this.head.pivot[0],this.head.pivot[1]);gl.uniform1f(loc("u_headDepthScale"),this.head.depthScale);gl.uniform1f(loc("u_headPerspective"),this.head.perspective);gl.uniform1f(loc("u_headYawGain"),this.head.yawGain);gl.uniform1f(loc("u_headPitchGain"),this.head.pitchGain);}
 private textureFor(item:VisualDrawItem):WebGLTexture{return(item.textureId?this.visualTextures.get(item.textureId):undefined)?.texture??this.whiteTexture.texture;}
 private ensureMasks(width:number,height:number):void{const{gl}=this;for(const key of this.plan.clipKeys){const old=this.maskTargets.get(key);if(old&&old.width===width&&old.height===height)continue;if(old){gl.deleteFramebuffer(old.framebuffer);gl.deleteTexture(old.texture);}const texture=gl.createTexture(),framebuffer=gl.createFramebuffer();if(!texture||!framebuffer)throw new Error("mask target allocation failed");gl.bindTexture(gl.TEXTURE_2D,texture);setTextureParams(gl,"linear");gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA8,width,height,0,gl.RGBA,gl.UNSIGNED_BYTE,null);gl.bindFramebuffer(gl.FRAMEBUFFER,framebuffer);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,texture,0);if(gl.checkFramebufferStatus(gl.FRAMEBUFFER)!==gl.FRAMEBUFFER_COMPLETE)throw new Error("mask framebuffer incomplete");this.maskTargets.set(key,{texture,framebuffer,width,height});}gl.bindFramebuffer(gl.FRAMEBUFFER,null);}
 private draw(program:WebGLProgram,gpu:PartGpu,item:VisualDrawItem):void{const{gl}=this,loc=(n:string)=>gl.getUniformLocation(program,n);gl.activeTexture(gl.TEXTURE3);gl.bindTexture(gl.TEXTURE_2D,this.textureFor(item));gl.uniform1i(loc("u_albedo"),3);gl.uniform1f(loc("u_opacity"),item.opacity);gl.bindVertexArray(gpu.vao);gl.drawElements(gl.TRIANGLES,gpu.indexCount,gpu.indexType,0);}
 private renderMasks(width:number,height:number):number{const{gl}=this;let calls=0;gl.enable(gl.BLEND);gl.blendFuncSeparate(gl.ONE,gl.ONE_MINUS_SRC_ALPHA,gl.ONE,gl.ONE_MINUS_SRC_ALPHA);this.common(this.maskProgram);for(const key of this.plan.clipKeys){const target=this.maskTargets.get(key),clip=this.plan.items.find(i=>i.clip?.key===key)?.clip;if(!target||!clip)continue;gl.bindFramebuffer(gl.FRAMEBUFFER,target.framebuffer);gl.viewport(0,0,width,height);gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT);for(const sourceIndex of clip.sourcePartIndices){const gpu=this.partByModelIndex.get(sourceIndex),item=this.plan.items.find(v=>v.partIndex===sourceIndex);if(!gpu||!item)continue;this.draw(this.maskProgram,gpu,item);calls++;}}gl.bindFramebuffer(gl.FRAMEBUFFER,null);return calls;}
 render():number{const{gl}=this,canvas=gl.canvas as HTMLCanvasElement,dpr=globalThis.devicePixelRatio||1,width=Math.max(1,Math.floor(canvas.clientWidth*dpr)),height=Math.max(1,Math.floor(canvas.clientHeight*dpr));if(canvas.width!==width||canvas.height!==height){canvas.width=width;canvas.height=height;}this.pollGpuQueries();this.flush();this.ensureMasks(width,height);const ext=this.timerExt;let query:WebGLQuery|null=null;if(this.gpuTimingEnabled&&ext){query=gl.createQuery();if(query)gl.beginQuery(ext.TIME_ELAPSED_EXT,query);}let drawCalls=this.renderMasks(width,height);gl.bindFramebuffer(gl.FRAMEBUFFER,null);gl.viewport(0,0,width,height);gl.clearColor(0.06,0.06,0.07,0);gl.clear(gl.COLOR_BUFFER_BIT);gl.enable(gl.BLEND);gl.blendFuncSeparate(gl.ONE,gl.ONE_MINUS_SRC_ALPHA,gl.ONE,gl.ONE_MINUS_SRC_ALPHA);this.common(this.mainProgram);const loc=(n:string)=>gl.getUniformLocation(this.mainProgram,n);gl.uniform2f(loc("u_viewport"),width,height);for(const item of this.plan.items){const gpu=this.partByModelIndex.get(item.partIndex);if(!gpu)continue;gl.activeTexture(gl.TEXTURE4);gl.bindTexture(gl.TEXTURE_2D,item.clip?this.maskTargets.get(item.clip.key)?.texture??this.whiteTexture.texture:this.whiteTexture.texture);gl.uniform1i(loc("u_mask"),4);gl.uniform1i(loc("u_clipMode"),item.clip?(item.clip.mode==="inside"?1:2):0);this.draw(this.mainProgram,gpu,item);drawCalls++;}gl.bindVertexArray(null);if(query&&ext){gl.endQuery(ext.TIME_ELAPSED_EXT);this.pendingQueries.push(query);}this.pollGpuQueries();return drawCalls;}
 destroy():void{this.gpuTimingEnabled=false;const{gl}=this;for(const q of this.pendingQueries.splice(0))gl.deleteQuery(q);for(const t of this.maskTargets.values()){gl.deleteFramebuffer(t.framebuffer);gl.deleteTexture(t.texture);}for(const t of this.visualTextures.values())gl.deleteTexture(t.texture);gl.deleteTexture(this.whiteTexture.texture);for(const p of this.parts){gl.deleteVertexArray(p.vao);for(const b of p.buffers)gl.deleteBuffer(b);}gl.deleteTexture(this.parameterTexture);gl.deleteTexture(this.parameterDefTexture);gl.deleteTexture(this.influenceTexture);gl.deleteProgram(this.mainProgram);gl.deleteProgram(this.maskProgram);}
}
