import type { AvatarModelV1, Part } from "@a2d/avatar-schema";
import { createTypedView, type LoadedA2DPackage } from "./packageLoader.js";
import { ParameterCore } from "./parameterCore.js";
import type { GpuTimingInfo } from "./gpuTiming.js";
import { compileVisualRenderPlan, type VisualDrawItem, type VisualRenderPlan } from "./visualPlan.js";
import { decodeVisualTextures, type DecodedVisualTextures } from "./visualTextures.js";
import type { DecodedTexture } from "./textureResources.js";
import { packWebGPUHeadUniforms, packWebGPUMorphInfluences, packWebGPUParameterDefinitions } from "./webgpuLayout.js";

type GpuBufferUsage=number; type GpuTextureUsage=number; type GpuMapMode=number;
type GpuFeatureSet={has(name:string):boolean};
type GpuBuffer={destroy():void;mapAsync(mode:number):Promise<void>;getMappedRange():ArrayBuffer;unmap():void};
type GpuTexture={createView():GpuTextureView;destroy():void}; type GpuTextureView=object; type GpuSampler=object;
type GpuShaderModule=object; type GpuBindGroup=object; type GpuBindGroupLayout=object; type GpuPipelineLayout=object; type GpuRenderPipeline=object; type GpuQuerySet={destroy():void};
type GpuRenderPass={setPipeline(p:GpuRenderPipeline):void;setBindGroup(i:number,g:GpuBindGroup):void;setVertexBuffer(slot:number,b:GpuBuffer):void;setIndexBuffer(b:GpuBuffer,format:"uint16"|"uint32"):void;drawIndexed(count:number):void;end():void};
type GpuCommandEncoder={beginRenderPass(d:unknown):GpuRenderPass;resolveQuerySet(q:GpuQuerySet,f:number,c:number,d:GpuBuffer,o:number):void;copyBufferToBuffer(s:GpuBuffer,so:number,d:GpuBuffer,doff:number,size:number):void;finish():object};
type GpuQueue={writeBuffer(b:GpuBuffer,o:number,data:ArrayBuffer|ArrayBufferView,dataOffset?:number,size?:number):void;writeTexture(dst:unknown,data:ArrayBuffer|ArrayBufferView,layout:unknown,size:unknown):void;copyExternalImageToTexture(src:unknown,dst:unknown,size:unknown):void;submit(commands:object[]):void};
type GpuDevice={queue:GpuQueue;lost:Promise<{message?:string}>;createBuffer(d:unknown):GpuBuffer;createTexture(d:unknown):GpuTexture;createSampler(d?:unknown):GpuSampler;createShaderModule(d:unknown):GpuShaderModule;createBindGroupLayout(d:unknown):GpuBindGroupLayout;createPipelineLayout(d:unknown):GpuPipelineLayout;createRenderPipeline(d:unknown):GpuRenderPipeline;createBindGroup(d:unknown):GpuBindGroup;createCommandEncoder(d?:unknown):GpuCommandEncoder;createQuerySet(d:unknown):GpuQuerySet;destroy():void};
type GpuAdapter={features:GpuFeatureSet;requestDevice(d?:{requiredFeatures?:string[]}):Promise<GpuDevice>};
type GpuApi={requestAdapter(o?:unknown):Promise<GpuAdapter|null>;getPreferredCanvasFormat():string};
type GpuCanvasContext={configure(d:unknown):void;getCurrentTexture():{createView():GpuTextureView}};
type TimingSlot={querySet:GpuQuerySet;resolveBuffer:GpuBuffer;readBuffer:GpuBuffer;pending:boolean;promise:Promise<void>|null};
type VisualTextureGpu={texture:GpuTexture;view:GpuTextureView;sampler:GpuSampler};
type PartGpu={modelIndex:number;part:Part;positionBuffer:GpuBuffer;uvBuffer:GpuBuffer;proxyZBuffer:GpuBuffer;influenceRangeBuffer:GpuBuffer;indexBuffer:GpuBuffer;indexCount:number;indexFormat:"uint16"|"uint32";visualUniform:GpuBuffer;maskBindGroup:GpuBindGroup;mainBindGroup:GpuBindGroup|null};
type MaskTarget={texture:GpuTexture;view:GpuTextureView;width:number;height:number};

const BU={MAP_READ:0x1,COPY_SRC:0x4,COPY_DST:0x8,INDEX:0x10,VERTEX:0x20,UNIFORM:0x40,STORAGE:0x80,QUERY_RESOLVE:0x200} as const satisfies Record<string,GpuBufferUsage>;
const TU={COPY_DST:0x2,TEXTURE_BINDING:0x4,RENDER_ATTACHMENT:0x10} as const satisfies Record<string,GpuTextureUsage>;
const MM={READ:0x1} as const satisfies Record<string,GpuMapMode>;
const MAX_VERTEX_INFLUENCES=8,TIMING_RING_SIZE=8,TIMESTAMP_BYTES=16;

const WGSL=`
struct HeadUniforms { head0:vec4<f32>, head1:vec4<f32>, parameterIndices:vec4<i32>, };
struct VisualUniforms { values:vec4<f32>, };
@group(0) @binding(0) var<storage,read> parameters:array<f32>;
@group(0) @binding(1) var<storage,read> parameterDefs:array<vec4<f32>>;
@group(0) @binding(2) var<storage,read> morphInfluences:array<vec4<f32>>;
@group(0) @binding(3) var<uniform> head:HeadUniforms;
@group(1) @binding(0) var visualSampler:sampler;
@group(1) @binding(1) var albedo:texture_2d<f32>;
@group(1) @binding(2) var maskTex:texture_2d<f32>;
@group(1) @binding(3) var<uniform> visual:VisualUniforms;
struct VI { @location(0) position:vec2<f32>, @location(1) uv:vec2<f32>, @location(2) proxyZ:f32, @location(3) influenceOffset:u32, @location(4) influenceCount:u32, };
struct VO { @builtin(position) position:vec4<f32>, @location(0) uv:vec2<f32>, };
fn norm(index:u32)->f32{let value=parameters[index];let def=parameterDefs[index];if(value>=def.z){let d=def.y-def.z;if(d==0.0){return 0.0;}return clamp((value-def.z)/d,0.0,1.0);}let d=def.z-def.x;if(d==0.0){return 0.0;}return clamp((value-def.z)/d,-1.0,0.0);}
fn param(index:i32)->f32{if(index<0){return 0.0;}return parameters[u32(index)];}
@vertex fn vsMain(input:VI)->VO{
 var p=input.position;let count=min(input.influenceCount,${MAX_VERTEX_INFLUENCES}u);
 for(var i=0u;i<${MAX_VERTEX_INFLUENCES}u;i=i+1u){if(i>=count){break;}let rec=morphInfluences[input.influenceOffset+i];p=p+norm(u32(round(rec.x)))*rec.w*rec.yz;}
 let ax=param(head.parameterIndices.x);let ay=param(head.parameterIndices.y);let az=param(head.parameterIndices.z);let pivot=head.head0.xy;let z0=input.proxyZ*head.head0.z;let yaw=radians(ax*head.head1.x);let pitch=radians(ay*head.head1.y);let cy=cos(yaw);let sy=sin(yaw);let cp=cos(pitch);let sp=sin(pitch);let local=p-pivot;let x1=cy*local.x+sy*z0;let z1=-sy*local.x+cy*z0;let y1=cp*local.y-sp*z1;let z2=sp*local.y+cp*z1;let scale=1.0/max(0.25,1.0+head.head0.w*(z2-z0));p=vec2<f32>(x1,y1)*scale+pivot;let r=radians(az);let cr=cos(r);let sr=sin(r);local=p-pivot;p=vec2<f32>(cr*local.x-sr*local.y,sr*local.x+cr*local.y)+pivot;var out:VO;out.position=vec4<f32>(p.x*2.0-1.0,1.0-p.y*2.0,0.0,1.0);out.uv=input.uv;return out;
}
@fragment fn fsMain(input:VO)->@location(0) vec4<f32>{var c=textureSample(albedo,visualSampler,input.uv)*visual.values.x;let mode=i32(round(visual.values.y));if(mode!=0){let dims=vec2<f32>(textureDimensions(maskTex));let uv=input.position.xy/max(dims,vec2<f32>(1.0));let coverage=textureSample(maskTex,visualSampler,uv).a;c=c*select(1.0-coverage,coverage,mode==1);}return c;}
@fragment fn fsMask(input:VO)->@location(0) vec4<f32>{let a=textureSample(albedo,visualSampler,input.uv).a*visual.values.x;return vec4<f32>(a,a,a,a);}
`;

function gpuApi():GpuApi|null{return (navigator as Navigator&{gpu?:GpuApi}).gpu??null;}
function buffer(device:GpuDevice,data:ArrayBufferView,usage:number,label:string):GpuBuffer{const size=Math.max(4,(data.byteLength+3)&~3);const b=device.createBuffer({label,size,usage:usage|BU.COPY_DST});if(data.byteLength)device.queue.writeBuffer(b,0,data);return b;}
function timingSlots(device:GpuDevice):TimingSlot[]{return Array.from({length:TIMING_RING_SIZE},(_,i)=>({querySet:device.createQuerySet({label:`a2d.visual.timing.${i}`,type:"timestamp",count:2}),resolveBuffer:device.createBuffer({size:TIMESTAMP_BYTES,usage:BU.QUERY_RESOLVE|BU.COPY_SRC}),readBuffer:device.createBuffer({size:TIMESTAMP_BYTES,usage:BU.COPY_DST|BU.MAP_READ}),pending:false,promise:null}));}
function visualUniform(device:GpuDevice,opacity:number,mode:number):GpuBuffer{return buffer(device,new Float32Array([opacity,mode,0,0]),BU.UNIFORM,"a2d.visual-uniform");}
function uploadTexture(device:GpuDevice,decoded:DecodedTexture):VisualTextureGpu{
 const texture=device.createTexture({size:{width:decoded.width,height:decoded.height,depthOrArrayLayers:1},format:"rgba8unorm",usage:TU.TEXTURE_BINDING|TU.COPY_DST});
 if(decoded.kind==="rgba8") device.queue.writeTexture({texture},decoded.pixels,{bytesPerRow:decoded.width*4,rowsPerImage:decoded.height},{width:decoded.width,height:decoded.height,depthOrArrayLayers:1});
 else device.queue.copyExternalImageToTexture({source:decoded.bitmap},{texture,premultipliedAlpha:true},{width:decoded.width,height:decoded.height});
 const sampler=device.createSampler({magFilter:decoded.filter,minFilter:decoded.filter,addressModeU:"clamp-to-edge",addressModeV:"clamp-to-edge"});return {texture,view:texture.createView(),sampler};
}
function whiteTexture(device:GpuDevice):VisualTextureGpu{const texture=device.createTexture({size:{width:1,height:1,depthOrArrayLayers:1},format:"rgba8unorm",usage:TU.TEXTURE_BINDING|TU.COPY_DST});device.queue.writeTexture({texture},new Uint8Array([255,255,255,255]),{bytesPerRow:4,rowsPerImage:1},{width:1,height:1,depthOrArrayLayers:1});return {texture,view:texture.createView(),sampler:device.createSampler({magFilter:"nearest",minFilter:"nearest"})};}

export class WebGPUVisualRenderer{
 readonly backend="webgpu" as const;readonly model:AvatarModelV1;readonly parameters:ParameterCore;readonly gpuTiming:GpuTimingInfo;
 private readonly canvas:HTMLCanvasElement;private readonly context:GpuCanvasContext;private readonly device:GpuDevice;private readonly format:string;private readonly commonLayout:GpuBindGroupLayout;private readonly visualLayout:GpuBindGroupLayout;private readonly mainPipeline:GpuRenderPipeline;private readonly maskPipeline:GpuRenderPipeline;private readonly commonBindGroup:GpuBindGroup;private readonly parameterBuffer:GpuBuffer;private readonly parameterDefBuffer:GpuBuffer;private readonly influenceBuffer:GpuBuffer;private readonly headBuffer:GpuBuffer;private readonly parts:PartGpu[]=[];private readonly partByIndex=new Map<number,PartGpu>();private readonly plan:VisualRenderPlan;private readonly textures=new Map<string,VisualTextureGpu>();private readonly white:VisualTextureGpu;private readonly masks=new Map<string,MaskTarget>();private readonly slots:TimingSlot[];private readonly samples:number[]=[];private gpuTimingEnabled=false;private lost=false;
 static isSupported():boolean{return gpuApi()!==null;}
 static async create(canvas:HTMLCanvasElement,pkg:LoadedA2DPackage):Promise<WebGPUVisualRenderer>{const api=gpuApi();if(!api)throw new Error("WebGPU is unavailable");const adapter=await api.requestAdapter({powerPreference:"high-performance"});if(!adapter)throw new Error("WebGPU adapter is unavailable");const ts=adapter.features.has("timestamp-query");const device=await adapter.requestDevice(ts?{requiredFeatures:["timestamp-query"]}:undefined);const context=canvas.getContext("webgpu") as unknown as GpuCanvasContext|null;if(!context){device.destroy();throw new Error("WebGPU canvas context is unavailable");}const decoded=await decodeVisualTextures(pkg);try{return new WebGPUVisualRenderer(canvas,pkg,device,context,api.getPreferredCanvasFormat(),ts,decoded);}finally{decoded.dispose();}}
 private constructor(canvas:HTMLCanvasElement,pkg:LoadedA2DPackage,device:GpuDevice,context:GpuCanvasContext,format:string,ts:boolean,decoded:DecodedVisualTextures){
  this.canvas=canvas;this.context=context;this.device=device;this.format=format;this.model=pkg.model;this.parameters=new ParameterCore(pkg.model.parameters);this.plan=compileVisualRenderPlan(pkg.model);this.gpuTiming=ts?{supported:true,source:"webgpu-timestamp-query"}:{supported:false,reason:"WebGPU adapter does not expose timestamp-query"};this.slots=ts?timingSlots(device):[];context.configure({device,format,alphaMode:"premultiplied",usage:TU.RENDER_ATTACHMENT});
  this.parameterBuffer=buffer(device,this.parameters.values.length?this.parameters.values:new Float32Array(1),BU.STORAGE,"a2d.parameters");this.parameterDefBuffer=buffer(device,packWebGPUParameterDefinitions(pkg.model.parameters),BU.STORAGE,"a2d.parameter-defs");this.influenceBuffer=buffer(device,packWebGPUMorphInfluences(pkg),BU.STORAGE,"a2d.influences");this.headBuffer=buffer(device,new Uint8Array(packWebGPUHeadUniforms(pkg.model,this.parameters.indexById)),BU.UNIFORM,"a2d.head");
  this.white=whiteTexture(device);for(const [id,t] of decoded.byId)this.textures.set(id,uploadTexture(device,t));
  const shader=device.createShaderModule({label:"a2d.visual",code:WGSL});
  this.commonLayout=device.createBindGroupLayout({entries:[{binding:0,visibility:1,buffer:{type:"read-only-storage"}},{binding:1,visibility:1,buffer:{type:"read-only-storage"}},{binding:2,visibility:1,buffer:{type:"read-only-storage"}},{binding:3,visibility:1,buffer:{type:"uniform"}}]});
  this.visualLayout=device.createBindGroupLayout({entries:[{binding:0,visibility:2,sampler:{type:"filtering"}},{binding:1,visibility:2,texture:{sampleType:"float"}},{binding:2,visibility:2,texture:{sampleType:"float"}},{binding:3,visibility:2,buffer:{type:"uniform"}}]});
  const layout=device.createPipelineLayout({bindGroupLayouts:[this.commonLayout,this.visualLayout]});
  const vertex={module:shader,entryPoint:"vsMain",buffers:[{arrayStride:8,attributes:[{shaderLocation:0,offset:0,format:"float32x2"}]},{arrayStride:8,attributes:[{shaderLocation:1,offset:0,format:"float32x2"}]},{arrayStride:4,attributes:[{shaderLocation:2,offset:0,format:"float32"}]},{arrayStride:8,attributes:[{shaderLocation:3,offset:0,format:"uint32"},{shaderLocation:4,offset:4,format:"uint32"}]}]};
  const blend={color:{srcFactor:"one",dstFactor:"one-minus-src-alpha",operation:"add"},alpha:{srcFactor:"one",dstFactor:"one-minus-src-alpha",operation:"add"}};
  this.mainPipeline=device.createRenderPipeline({layout,vertex,fragment:{module:shader,entryPoint:"fsMain",targets:[{format,blend}]},primitive:{topology:"triangle-list",cullMode:"none"}});
  this.maskPipeline=device.createRenderPipeline({layout,vertex,fragment:{module:shader,entryPoint:"fsMask",targets:[{format:"rgba8unorm",blend}]},primitive:{topology:"triangle-list",cullMode:"none"}});
  this.commonBindGroup=device.createBindGroup({layout:this.commonLayout,entries:[{binding:0,resource:{buffer:this.parameterBuffer}},{binding:1,resource:{buffer:this.parameterDefBuffer}},{binding:2,resource:{buffer:this.influenceBuffer}},{binding:3,resource:{buffer:this.headBuffer}}]});
  pkg.model.parts.forEach((part,i)=>{const gpu=this.createPart(pkg,part,i);this.parts.push(gpu);this.partByIndex.set(i,gpu);});this.rebuildVisualBindGroups();void device.lost.then(info=>{this.lost=true;console.error(`A2D WebGPU device lost${info.message?`: ${info.message}`:""}`);});
 }
 private textureFor(item:VisualDrawItem):VisualTextureGpu{return (item.textureId?this.textures.get(item.textureId):undefined)??this.white;}
 private createPart(pkg:LoadedA2DPackage,part:Part,modelIndex:number):PartGpu{const positions=createTypedView(pkg.buffers,part.mesh.positions),uvs=createTypedView(pkg.buffers,part.mesh.uvs),indices=createTypedView(pkg.buffers,part.mesh.indices);if(!(positions instanceof Float32Array)||!(uvs instanceof Float32Array))throw new Error(`${part.id}: positions/uvs must be f32`);if(!(indices instanceof Uint16Array||indices instanceof Uint32Array))throw new Error(`${part.id}: indices must be u16/u32`);const n=positions.length/2;let z=new Float32Array(n),ranges=new Uint32Array(n*2);if(part.mesh.proxyZ){const v=createTypedView(pkg.buffers,part.mesh.proxyZ);if(!(v instanceof Float32Array)||v.length!==n)throw new Error(`${part.id}: invalid proxyZ`);z=v;}if(part.mesh.influenceRanges){const v=createTypedView(pkg.buffers,part.mesh.influenceRanges);if(!(v instanceof Uint32Array)||v.length!==n*2)throw new Error(`${part.id}: invalid influenceRanges`);ranges=v;}const item=this.plan.items.find(v=>v.partIndex===modelIndex);if(!item)throw new Error(`visual item missing: ${part.id}`);const uniform=visualUniform(this.device,item.opacity,item.clip?(item.clip.mode==="inside"?1:2):0);const texture=this.textureFor(item);const maskBindGroup=this.device.createBindGroup({layout:this.visualLayout,entries:[{binding:0,resource:texture.sampler},{binding:1,resource:texture.view},{binding:2,resource:this.white.view},{binding:3,resource:{buffer:uniform}}]});return {modelIndex,part,positionBuffer:buffer(this.device,positions,BU.VERTEX,`${part.id}.pos`),uvBuffer:buffer(this.device,uvs,BU.VERTEX,`${part.id}.uv`),proxyZBuffer:buffer(this.device,z,BU.VERTEX,`${part.id}.z`),influenceRangeBuffer:buffer(this.device,ranges,BU.VERTEX,`${part.id}.ranges`),indexBuffer:buffer(this.device,indices,BU.INDEX,`${part.id}.idx`),indexCount:indices.length,indexFormat:indices instanceof Uint32Array?"uint32":"uint16",visualUniform:uniform,maskBindGroup,mainBindGroup:null};}
 private ensureMasks(width:number,height:number):void{let changed=false;for(const key of this.plan.clipKeys){const old=this.masks.get(key);if(old&&old.width===width&&old.height===height)continue;if(old)old.texture.destroy();const texture=this.device.createTexture({size:{width,height,depthOrArrayLayers:1},format:"rgba8unorm",usage:TU.RENDER_ATTACHMENT|TU.TEXTURE_BINDING});this.masks.set(key,{texture,view:texture.createView(),width,height});changed=true;}if(changed)this.rebuildVisualBindGroups();}
 private rebuildVisualBindGroups():void{for(const item of this.plan.items){const gpu=this.partByIndex.get(item.partIndex);if(!gpu)continue;const texture=this.textureFor(item);const maskView=item.clip?this.masks.get(item.clip.key)?.view??this.white.view:this.white.view;gpu.mainBindGroup=this.device.createBindGroup({layout:this.visualLayout,entries:[{binding:0,resource:texture.sampler},{binding:1,resource:texture.view},{binding:2,resource:maskView},{binding:3,resource:{buffer:gpu.visualUniform}}]});}}
 private setGeometry(pass:GpuRenderPass,p:PartGpu):void{pass.setVertexBuffer(0,p.positionBuffer);pass.setVertexBuffer(1,p.uvBuffer);pass.setVertexBuffer(2,p.proxyZBuffer);pass.setVertexBuffer(3,p.influenceRangeBuffer);pass.setIndexBuffer(p.indexBuffer,p.indexFormat);}
 setParameter(id:string,value:number):void{this.parameters.set(id,value);}setGpuTimingEnabled(enabled:boolean):void{this.gpuTimingEnabled=enabled&&this.gpuTiming.supported;}
 async collectGpuTimings():Promise<number[]>{const pending=this.slots.map(s=>s.promise).filter((p):p is Promise<void>=>p!==null);if(pending.length)await Promise.allSettled(pending);return this.samples.splice(0);}
 private flush():void{const r=this.parameters.consumeDirtyRange();if(r)this.device.queue.writeBuffer(this.parameterBuffer,r.start*4,this.parameters.values.subarray(r.start,r.endExclusive));}
 private slot():TimingSlot|null{return this.gpuTimingEnabled?(this.slots.find(s=>!s.pending)??null):null;}
 private readback(s:TimingSlot):void{s.pending=true;s.promise=s.readBuffer.mapAsync(MM.READ).then(()=>{const a=new BigUint64Array(s.readBuffer.getMappedRange().slice(0,TIMESTAMP_BYTES));const ns=a[1]>=a[0]?a[1]-a[0]:0n;const ms=Number(ns)/1_000_000;if(Number.isFinite(ms)&&ms>=0)this.samples.push(ms);s.readBuffer.unmap();}).catch(()=>{}).finally(()=>{s.pending=false;s.promise=null;});}
 render():number{if(this.lost)return 0;const dpr=globalThis.devicePixelRatio||1,width=Math.max(1,Math.floor(this.canvas.clientWidth*dpr)),height=Math.max(1,Math.floor(this.canvas.clientHeight*dpr));if(this.canvas.width!==width||this.canvas.height!==height){this.canvas.width=width;this.canvas.height=height;}this.flush();this.ensureMasks(width,height);const timing=this.slot(),encoder=this.device.createCommandEncoder({label:"a2d.visual.frame"});let drawCalls=0,firstMask=true;
  for(const key of this.plan.clipKeys){const target=this.masks.get(key),clip=this.plan.items.find(i=>i.clip?.key===key)?.clip;if(!target||!clip)continue;const desc:Record<string,unknown>={colorAttachments:[{view:target.view,clearValue:{r:0,g:0,b:0,a:0},loadOp:"clear",storeOp:"store"}]};if(timing&&firstMask){desc.timestampWrites={querySet:timing.querySet,beginningOfPassWriteIndex:0};firstMask=false;}const pass=encoder.beginRenderPass(desc);pass.setPipeline(this.maskPipeline);pass.setBindGroup(0,this.commonBindGroup);for(const idx of clip.sourcePartIndices){const p=this.partByIndex.get(idx);if(!p)continue;pass.setBindGroup(1,p.maskBindGroup);this.setGeometry(pass,p);pass.drawIndexed(p.indexCount);drawCalls++;}pass.end();}
  const mainDesc:Record<string,unknown>={colorAttachments:[{view:this.context.getCurrentTexture().createView(),clearValue:{r:0.06,g:0.06,b:0.07,a:0},loadOp:"clear",storeOp:"store"}]};if(timing)mainDesc.timestampWrites=this.plan.clipKeys.size===0?{querySet:timing.querySet,beginningOfPassWriteIndex:0,endOfPassWriteIndex:1}:{querySet:timing.querySet,endOfPassWriteIndex:1};const pass=encoder.beginRenderPass(mainDesc);pass.setPipeline(this.mainPipeline);pass.setBindGroup(0,this.commonBindGroup);for(const item of this.plan.items){const p=this.partByIndex.get(item.partIndex);if(!p||!p.mainBindGroup)continue;pass.setBindGroup(1,p.mainBindGroup);this.setGeometry(pass,p);pass.drawIndexed(p.indexCount);drawCalls++;}pass.end();if(timing){encoder.resolveQuerySet(timing.querySet,0,2,timing.resolveBuffer,0);encoder.copyBufferToBuffer(timing.resolveBuffer,0,timing.readBuffer,0,TIMESTAMP_BYTES);}this.device.queue.submit([encoder.finish()]);if(timing)this.readback(timing);return drawCalls;}
 destroy():void{this.gpuTimingEnabled=false;for(const s of this.slots){s.querySet.destroy();s.resolveBuffer.destroy();s.readBuffer.destroy();}for(const m of this.masks.values())m.texture.destroy();for(const t of this.textures.values())t.texture.destroy();this.white.texture.destroy();for(const p of this.parts){p.positionBuffer.destroy();p.uvBuffer.destroy();p.proxyZBuffer.destroy();p.influenceRangeBuffer.destroy();p.indexBuffer.destroy();p.visualUniform.destroy();}this.parameterBuffer.destroy();this.parameterDefBuffer.destroy();this.influenceBuffer.destroy();this.headBuffer.destroy();this.device.destroy();this.parts.length=0;}
}
